# Assignment 1

#### Due Date: 24th Jan'18

In this assignment we will cover the basics of Machine Learning. We will cover the following topics:

1) Linear Regression

2) Logistic Regression

3) EM Algorithm

4) K-means/Hirarchical Clustering.

It is crucial to get down to the nitty gritty of the code to implement all of these. No external packages (like scipy), which directly give functions for these algorithms, are to be used. 

## Linear Regression

Defination: Given a data set ${\displaystyle \{y_{i},\,x_{i1},\ldots ,x_{ip}\}_{i=1}^{n}} $ of $n$ statistical units, a linear regression model assumes that the relationship between the dependent variable $y_i$ and the $p$-vector of regressors $x_i$ is linear. This relationship is modeled through a disturbance term or error variable $ε_i$ - an unobserved random variable that adds noise to the linear relationship between the dependent variable and regressors. Thus the model takes the form:

$$ {\displaystyle \mathbf {y} =X{\boldsymbol {\beta }}+{\boldsymbol {\varepsilon }},\,} $$

where,

$$ \mathbf {y} ={\begin{pmatrix}y_{1}\\y_{2}\\\vdots \\y_{n}\end{pmatrix}},\quad $$

$$ {\displaystyle X={\begin{pmatrix}\mathbf {x} _{1}^{\top }\\\mathbf {x} _{2}^{\top }\\\vdots \\\mathbf {x} _{n}^{\top }\end{pmatrix}}={\begin{pmatrix}1&x_{11}&\cdots &x_{1p}\\1&x_{21}&\cdots &x_{2p}\\\vdots &\vdots &\ddots &\vdots \\1&x_{n1}&\cdots &x_{np}\end{pmatrix}},}
$$

$$ {\displaystyle {\boldsymbol {\beta }}={\begin{pmatrix}\beta _{0}\\\beta _{1}\\\beta _{2}\\\vdots \\\beta _{p}\end{pmatrix}},\quad {\boldsymbol {\varepsilon }}={\begin{pmatrix}\varepsilon _{1}\\\varepsilon _{2}\\\vdots \\\varepsilon _{n}\end{pmatrix}}.} 
$$


For this problem, in the class lecture we covered the Least Square Solution, which can be formulated as:

$${\displaystyle {\hat {\boldsymbol {\beta }}}=(\mathbf {X} ^{\top }\mathbf {X} )^{-1}\mathbf {X} ^{\top }\mathbf {y} =\left(\sum \mathbf {x} _{i}\mathbf {x} _{i}^{\top }\right)^{-1}\left(\sum \mathbf {x} _{i}y_{i}\right).} $$

## Question 1

a) You will write the code to find the LSS for the given data. The data contains 3 columns, each for $y, X_{1}$, and $X_{2}$ respectively. Few of the possible models are:

$$ {\displaystyle \mathbf {y} ={\boldsymbol {\beta_{1} }}X_1+{\boldsymbol {\beta_{0} }}+{\boldsymbol {\varepsilon }},\,} $$


$$ {\displaystyle \mathbf {y} ={\boldsymbol {\beta_{2} }}X_2+{\boldsymbol {\beta_{0} }}+{\boldsymbol {\varepsilon }},\,} $$


$$ {\displaystyle \mathbf {y} ={\boldsymbol {\beta_{1} }}X_1+ {\boldsymbol {\beta_{2} }}X_2+{\boldsymbol {\beta_{0} }}+{\boldsymbol {\varepsilon }},\,} $$

Given this data, find the coefficients for each of these models.

b) Now that you have three models, you must select the best one. Use Cross-validation with 5 folds on the dataset to find the optimal model (On the basis of RMSE on the test partition). 

In [10]:
import numpy
from math import sqrt
# Load the dataset 
train_data = np.load('utils/assign_1_data_1_train.npy')
# now write the code for finding the solution for each of the three models.

#Note the data format is assumed to be X1,X2,y

#Scoring functions
def RMSE(Y, Y_hat,n):
	return sqrt(np.sum(np.square(Y-Y_hat), axis=0)/n)


def SSE(Y, Y_hat,n):
	return RMSE(Y,Y_hat,n) * n

def TSS(Y, Y_hat,n):
	y_bar = np.sum(Y, axis=0)/n
	return np.sum(np.square(Y-y_bar),axis=0)

def R_square(Y, Y_hat,n):
	 return 1-(SSE(Y, Y_hat,n)/TSS(Y, Y_hat,n))

In [ ]:
# Finally, Write The estimates of the betas here:

# Model 1
def model1Train(data):
	X = np.reshape(data[:,0],(240,1))
	X = np.insert(X,0,np.ones(240),axis=1)
	Y = np.reshape(data[:,2], (240,1))
	B = np.linalg.solve(np.matmul(np.transpose(X),X), np.matmul(np.transpose(X),Y))
	return B

def model1Test(data, B):
	X = np.reshape(data[:,0],(60,1))
	X = np.insert(X,0,np.ones(60),axis=1)
	Y = data[:,2]
	#print Y_hat
	Y = np.reshape(Y,(60,1))
	Y_hat = np.matmul(X,np.reshape(B,(2,1)))
	#print Y_hat
	return RMSE(Y, Y_hat,60)

# Model 2
def model2Train(data):
	X = np.reshape(data[:,1],(240,1))
	X = np.insert(X,0,np.ones(240),axis=1)
	Y = data[:,2]
	B = np.linalg.solve(np.matmul(np.transpose(X),X), np.matmul(np.transpose(X),Y))
	return B

def model2Test(data, B):
	X = np.reshape(data[:,1],(60,1))
	X = np.insert(X,0,np.ones(60),axis=1)
	Y = data[:,2]
	#print Y_hat
	Y = np.reshape(Y,(60,1))
	Y_hat = np.matmul(X,np.reshape(B,(2,1)))
	#print Y
	return RMSE(Y, Y_hat, 60)
# Model 3
def model3Train(data):
	X = data[:,0:2]
	X = np.insert(X,0,np.ones(240),axis=1)
	Y = data[:,2]
	B = np.linalg.solve(np.matmul(np.transpose(X),X), np.matmul(np.transpose(X),Y))
	return B

def model3Test(data, B):
	X = data[:,0:2]
	X = np.insert(X,0,np.ones(60),axis=1)
	Y = data[:,2]
	Y = np.reshape(Y,(60,1))
	#print Y_hat.shape
	Y_hat = np.matmul(X,np.reshape(B,(3,1)))
	#print Y.shape
	return RMSE(Y, Y_hat, 60)

def model3TestR2(data, B):
	X = data[:,0:2]
	X = np.insert(X,0,np.ones(150),axis=1)
	Y = data[:,2]
	Y = np.reshape(Y,(150,1))
	#print Y_hat.shape
	Y_hat = np.matmul(X,np.reshape(B,(3,1)))
	#print Y.shape
	return R_square(Y, Y_hat, 150)

In [11]:
# partition the dataset into 5 random folds.

# for each fold, approx. model from the remaining folds, and calculate RMSE on the test fold.

# find avg RMSE for each model. 

# Which is the best model?
RMSE_A = 0
RMSE_B = 0
RMSE_C = 0
for i in range(5):
	train_data = np.roll(train_data, 60, axis=0)

	B1 = model1Train(train_data[0:240,:])
	RMSE_A += model1Test(train_data[240:300,:], B1)

	B2 = model2Train(train_data[0:240,:])
	RMSE_B += model2Test(train_data[240:300,:], B2)

	B3 = model3Train(train_data[0:240,:])
	RMSE_C += model3Test(train_data[240:300,:], B3)

print 'Average RMSEs'
print 'A ', RMSE_A/5, 'B: ', RMSE_B/5, 'C: ', RMSE_C/5



Average RMSEs
A  71.2882051869 B:  71.9204010094 C:  71.223145557


In [12]:
# Finally, Give the R^2 score of the best model in the test set:
#Since C is the best Model
test_data = np.load('utils/assign_1_data_1_test.npy')
print model3TestR2(test_data, B3)



[ 0.9861672]


In [13]:
# Bonus

# Show a graph between the predicted Y^ and the Ground truth Y

# Try to plot Y vs X_1 in train set.

# can it help you improve your model?
# construct the better model.

# Logistic Regression

Generaly, Logistic Regression is used to predict categorial variables. For the simple problem of 2-way classification, the output $\hat{y_i}$ is modeled as the probability that $\{X_i\}$ belongs to class $1$ (given two classes $0$, and $1$).

$$ P( \{X_i\} \in Set_1 ) = \hat{y_i}, $$ ( $y_i$ is the actual label; $y_i \in \{ 0,1 \}$ )


$\hat{y_i}$ is typically modeled as the output of a sigmoid on a linear combination of the input feature $\{X_i\}$:

$$ \mathbf {\hat{y}} = \sigma(X{\boldsymbol {\beta }}+{\boldsymbol {\varepsilon }}) = \sigma_\beta(X)$$

Now, The likelihood of some given data for this model can be written as:

$${\displaystyle {\begin{aligned}L(\beta |x)&=Pr(Y|X;\beta )\\&=\prod _{i}Pr(y_{i}|x_{i};\beta )\\&=\prod _{i}\sigma_{\beta }(x_{i})^{y_{i}}(1-\sigma_{\beta }(x_{i}))^{(1-y_{i})}\end{aligned}}}$$

Unlike in the case of Linear regression, this equation has no closed form solution. Hence we will use gradient descent on the negative log-likelihood $J(\beta)$ to find the optimal $\beta$

$$
J(\beta) = \sum_i{\big( y_ilog(\hat{y_i})+ (1-y_i)log(1-\hat{y_i}) \big) }
$$

with the update equation:

$$
\beta_j = \beta_j + \alpha \times \frac{ \partial J(\beta)}{\partial \beta}
$$

## Question 2

a) You will write the code to find the optimal logistic regression model for the given data. The data contains 3 columns, each for $y, X_{1}$, and $X_{2}$ respectively. For the rate of learning $\alpha$ use a linearly decaying policy, or step-wise reduction policy. 

$$ {\displaystyle \mathbf {y} =\sigma \big( {\boldsymbol {\beta_{1} }}X_1+ {\boldsymbol {\beta_{2} }}X_2+{\boldsymbol {\beta_{0} }}+{\boldsymbol {\varepsilon }}} \big) $$

b) Explore possible methods of adjusting the learning rate $\alpha$ 

In [23]:
from math import exp
# Load the train dataset 
train_data = np.load('utils/assign_1_data_2_train.npy')
# now write the code to find the parameters of the optimization.
learning_rate = 0.005
weights = np.random.rand(3,1)
print weights.shape
def score(data, weights):
	y_hat = np.sum(np.multiply(data[1:,:],weights[1:,:]), axis=0) + weights[0]
	return 1.0/(1.0 + exp(-y_hat))


(3, 1)


In [24]:
# test on a validation part every 't' iterations to find when you start overfitting.
# t = ?
stopping_criteria = 5
t = 0
flag = 0
previous_s_e = np.array([999.0])
previous_v_e = np.array([999.0])
while True:
	t +=1
	squared_error = 0
	print "Currently in iteration ", t
	#train_data = np.roll(train_data, 60, axis=0)
	for k in range(240):
		data = np.reshape(train_data[k], (3,1))
		#print data.shape
		predicted = score(data, weights)
		error = data[0] - predicted
		squared_error += error**2
		weights[1:,:] = weights[1:,:] + learning_rate*error*predicted*(1-predicted)*data[1:,:]
		weights[0] = weights[0] + learning_rate*error*predicted*(1-predicted)
	#print "Training error is ",squared_error
	validation_error = 0
	for k in range(240,300):
		data = np.reshape(train_data[k], (3,1))
		#print data.shape
		predicted = score(data, weights)
		error = data[0] - predicted
		validation_error += error**2
	if squared_error[0] < previous_s_e[0] and validation_error[0] > previous_v_e[0]:
		stopping_criteria -=1
		flag = 1
		if stopping_criteria == 0:
			break
	if squared_error[0] < previous_s_e[0] and validation_error[0] < previous_v_e[0] and flag == 1:
		stopping_criteria +=1
		if stopping_criteria == 5:
			flag = 0
	previous_v_e = validation_error
	previous_s_e = squared_error
print t
# Now for 't' iterations train on the entire dataset for testing on the test_data


Currently in iteration  1
Currently in iteration  2
Currently in iteration  3
Currently in iteration  4
Currently in iteration  5
Currently in iteration  6
Currently in iteration  7
Currently in iteration  8
Currently in iteration  9
Currently in iteration  10
Currently in iteration  11
Currently in iteration  12
Currently in iteration  13
Currently in iteration  14
Currently in iteration  15
Currently in iteration  16
Currently in iteration  17
Currently in iteration  18
Currently in iteration  19
Currently in iteration  20
Currently in iteration  21
Currently in iteration  22
Currently in iteration  23
Currently in iteration  24
Currently in iteration  25
Currently in iteration  26
Currently in iteration  27
Currently in iteration  28
Currently in iteration  29
Currently in iteration  30
Currently in iteration  31
Currently in iteration  32
Currently in iteration  33
Currently in iteration  34
Currently in iteration  35
Currently in iteration  36
Currently in iteration  37
Currently 

Currently in iteration  302
Currently in iteration  303
Currently in iteration  304
Currently in iteration  305
Currently in iteration  306
Currently in iteration  307
Currently in iteration  308
Currently in iteration  309
Currently in iteration  310
Currently in iteration  311
Currently in iteration  312
Currently in iteration  313
Currently in iteration  314
Currently in iteration  315
Currently in iteration  316
Currently in iteration  317
Currently in iteration  318
Currently in iteration  319
Currently in iteration  320
Currently in iteration  321
Currently in iteration  322
Currently in iteration  323
Currently in iteration  324
Currently in iteration  325
Currently in iteration  326
Currently in iteration  327
Currently in iteration  328
Currently in iteration  329
Currently in iteration  330
Currently in iteration  331
Currently in iteration  332
Currently in iteration  333
Currently in iteration  334
Currently in iteration  335
Currently in iteration  336
Currently in iterati

Currently in iteration  596
Currently in iteration  597
Currently in iteration  598
Currently in iteration  599
Currently in iteration  600
Currently in iteration  601
Currently in iteration  602
Currently in iteration  603
Currently in iteration  604
Currently in iteration  605
Currently in iteration  606
Currently in iteration  607
Currently in iteration  608
Currently in iteration  609
Currently in iteration  610
Currently in iteration  611
Currently in iteration  612
Currently in iteration  613
Currently in iteration  614
Currently in iteration  615
Currently in iteration  616
Currently in iteration  617
Currently in iteration  618
Currently in iteration  619
Currently in iteration  620
Currently in iteration  621
Currently in iteration  622
Currently in iteration  623
Currently in iteration  624
Currently in iteration  625
Currently in iteration  626
Currently in iteration  627
Currently in iteration  628
Currently in iteration  629
Currently in iteration  630
Currently in iterati

Currently in iteration  915
Currently in iteration  916
Currently in iteration  917
Currently in iteration  918
Currently in iteration  919
Currently in iteration  920
Currently in iteration  921
Currently in iteration  922
Currently in iteration  923
Currently in iteration  924
Currently in iteration  925
Currently in iteration  926
Currently in iteration  927
Currently in iteration  928
Currently in iteration  929
Currently in iteration  930
Currently in iteration  931
Currently in iteration  932
Currently in iteration  933
Currently in iteration  934
Currently in iteration  935
Currently in iteration  936
Currently in iteration  937
Currently in iteration  938
Currently in iteration  939
Currently in iteration  940
Currently in iteration  941
Currently in iteration  942
Currently in iteration  943
Currently in iteration  944
Currently in iteration  945
Currently in iteration  946
Currently in iteration  947
Currently in iteration  948
Currently in iteration  949
Currently in iterati

Currently in iteration  1207
Currently in iteration  1208
Currently in iteration  1209
Currently in iteration  1210
Currently in iteration  1211
Currently in iteration  1212
Currently in iteration  1213
Currently in iteration  1214
Currently in iteration  1215
Currently in iteration  1216
Currently in iteration  1217
Currently in iteration  1218
Currently in iteration  1219
Currently in iteration  1220
Currently in iteration  1221
Currently in iteration  1222
Currently in iteration  1223
Currently in iteration  1224
Currently in iteration  1225
Currently in iteration  1226
Currently in iteration  1227
Currently in iteration  1228
Currently in iteration  1229
Currently in iteration  1230
Currently in iteration  1231
Currently in iteration  1232
Currently in iteration  1233
Currently in iteration  1234
Currently in iteration  1235
Currently in iteration  1236
Currently in iteration  1237
Currently in iteration  1238
Currently in iteration  1239
Currently in iteration  1240
Currently in i

Currently in iteration  1498
Currently in iteration  1499
Currently in iteration  1500
Currently in iteration  1501
Currently in iteration  1502
Currently in iteration  1503
Currently in iteration  1504
Currently in iteration  1505
Currently in iteration  1506
Currently in iteration  1507
Currently in iteration  1508
Currently in iteration  1509
Currently in iteration  1510
Currently in iteration  1511
Currently in iteration  1512
Currently in iteration  1513
Currently in iteration  1514
Currently in iteration  1515
Currently in iteration  1516
Currently in iteration  1517
Currently in iteration  1518
Currently in iteration  1519
Currently in iteration  1520
Currently in iteration  1521
Currently in iteration  1522
Currently in iteration  1523
Currently in iteration  1524
Currently in iteration  1525
Currently in iteration  1526
Currently in iteration  1527
Currently in iteration  1528
Currently in iteration  1529
Currently in iteration  1530
Currently in iteration  1531
Currently in i

Currently in iteration  1792
Currently in iteration  1793
Currently in iteration  1794
Currently in iteration  1795
Currently in iteration  1796
Currently in iteration  1797
Currently in iteration  1798
Currently in iteration  1799
Currently in iteration  1800
Currently in iteration  1801
Currently in iteration  1802
Currently in iteration  1803
Currently in iteration  1804
Currently in iteration  1805
Currently in iteration  1806
Currently in iteration  1807
Currently in iteration  1808
Currently in iteration  1809
Currently in iteration  1810
Currently in iteration  1811
Currently in iteration  1812
Currently in iteration  1813
Currently in iteration  1814
Currently in iteration  1815
Currently in iteration  1816
Currently in iteration  1817
Currently in iteration  1818
Currently in iteration  1819
Currently in iteration  1820
Currently in iteration  1821
Currently in iteration  1822
Currently in iteration  1823
Currently in iteration  1824
Currently in iteration  1825
Currently in i

Currently in iteration  2081
Currently in iteration  2082
Currently in iteration  2083
Currently in iteration  2084
Currently in iteration  2085
Currently in iteration  2086
Currently in iteration  2087
Currently in iteration  2088
Currently in iteration  2089
Currently in iteration  2090
Currently in iteration  2091
Currently in iteration  2092
Currently in iteration  2093
Currently in iteration  2094
Currently in iteration  2095
Currently in iteration  2096
Currently in iteration  2097
Currently in iteration  2098
Currently in iteration  2099
Currently in iteration  2100
Currently in iteration  2101
Currently in iteration  2102
Currently in iteration  2103
Currently in iteration  2104
Currently in iteration  2105
Currently in iteration  2106
Currently in iteration  2107
Currently in iteration  2108
Currently in iteration  2109
Currently in iteration  2110
Currently in iteration  2111
Currently in iteration  2112
Currently in iteration  2113
Currently in iteration  2114
Currently in i

Currently in iteration  2371
Currently in iteration  2372
Currently in iteration  2373
Currently in iteration  2374
Currently in iteration  2375
Currently in iteration  2376
Currently in iteration  2377
Currently in iteration  2378
Currently in iteration  2379
Currently in iteration  2380
Currently in iteration  2381
Currently in iteration  2382
Currently in iteration  2383
Currently in iteration  2384
Currently in iteration  2385
Currently in iteration  2386
Currently in iteration  2387
Currently in iteration  2388
Currently in iteration  2389
Currently in iteration  2390
Currently in iteration  2391
Currently in iteration  2392
Currently in iteration  2393
Currently in iteration  2394
Currently in iteration  2395
Currently in iteration  2396
Currently in iteration  2397
Currently in iteration  2398
Currently in iteration  2399
Currently in iteration  2400
Currently in iteration  2401
Currently in iteration  2402
Currently in iteration  2403
Currently in iteration  2404
Currently in i

Currently in iteration  2673
Currently in iteration  2674
Currently in iteration  2675
Currently in iteration  2676
Currently in iteration  2677
Currently in iteration  2678
Currently in iteration  2679
Currently in iteration  2680
Currently in iteration  2681
Currently in iteration  2682
Currently in iteration  2683
Currently in iteration  2684
Currently in iteration  2685
Currently in iteration  2686
Currently in iteration  2687
Currently in iteration  2688
Currently in iteration  2689
Currently in iteration  2690
Currently in iteration  2691
Currently in iteration  2692
Currently in iteration  2693
Currently in iteration  2694
Currently in iteration  2695
Currently in iteration  2696
Currently in iteration  2697
Currently in iteration  2698
Currently in iteration  2699
Currently in iteration  2700
Currently in iteration  2701
Currently in iteration  2702
Currently in iteration  2703
Currently in iteration  2704
Currently in iteration  2705
Currently in iteration  2706
Currently in i

Currently in iteration  2971
Currently in iteration  2972
Currently in iteration  2973
Currently in iteration  2974
Currently in iteration  2975
Currently in iteration  2976
Currently in iteration  2977
Currently in iteration  2978
Currently in iteration  2979
Currently in iteration  2980
Currently in iteration  2981
Currently in iteration  2982
Currently in iteration  2983
Currently in iteration  2984
Currently in iteration  2985
Currently in iteration  2986
Currently in iteration  2987
Currently in iteration  2988
Currently in iteration  2989
Currently in iteration  2990
Currently in iteration  2991
Currently in iteration  2992
Currently in iteration  2993
Currently in iteration  2994
Currently in iteration  2995
Currently in iteration  2996
Currently in iteration  2997
Currently in iteration  2998
Currently in iteration  2999
Currently in iteration  3000
Currently in iteration  3001
Currently in iteration  3002
Currently in iteration  3003
Currently in iteration  3004
Currently in i

Currently in iteration  3270
Currently in iteration  3271
Currently in iteration  3272
Currently in iteration  3273
Currently in iteration  3274
Currently in iteration  3275
Currently in iteration  3276
Currently in iteration  3277
Currently in iteration  3278
Currently in iteration  3279
Currently in iteration  3280
Currently in iteration  3281
Currently in iteration  3282
Currently in iteration  3283
Currently in iteration  3284
Currently in iteration  3285
Currently in iteration  3286
Currently in iteration  3287
Currently in iteration  3288
Currently in iteration  3289
Currently in iteration  3290
Currently in iteration  3291
Currently in iteration  3292
Currently in iteration  3293
Currently in iteration  3294
Currently in iteration  3295
Currently in iteration  3296
Currently in iteration  3297
Currently in iteration  3298
Currently in iteration  3299
Currently in iteration  3300
Currently in iteration  3301
Currently in iteration  3302
Currently in iteration  3303
Currently in i

In [ ]:
# find the accuracy on the test set:
test_data = np.load('utils/assign_1_data_2_test.npy')

final_error = 0
for k in range(150):
	data = np.reshape(test_data[k], (3,1))
	#print data.shape
	predicted = score(data, weights)
	error = data[0] - predicted
	final_error += error**2
print final_error

In [ ]:
# Bonus
# Can you adjust the learning rate alpha in a better way?


# EM algorithm

This is a general framework for likelihood-based parameter estimation.
A basic outline of this algorithm is:

* start with initial guesses of parameters

* E step: estimate memberships given params

* M step: estimate params given memberships

* Repeat until convergence

** Refer to [this link](http://www.rmki.kfki.hu/~banmi/elte/bishop_em.pdf) (9.2.2) .**


## Question 3

Let ${\displaystyle \mathbf {x} =(\mathbf {x} _{1},\mathbf {x} _{2},\ldots ,\mathbf {x} _{n})} $ be a sample of $n$ independent observations from a mixture of two multivariate normal distributions of dimension $d$ , and let ${\displaystyle \mathbf {z} =(z_{1},z_{2},\ldots ,z_{n})} $ be the latent variables that determine the component from which the observation originates.

$X_i |(Z_i = 1) \sim \mathcal{N}_d(\boldsymbol{\mu}_1,\Sigma_1)$ and $X_i |(Z_i = 2) \sim \mathcal{N}_d(\boldsymbol{\mu}_2,\Sigma_2)$

The aim is to estimate the unknown parameters representing the mixing value between the Gaussians and the means and covariances of each:

$$ \theta = \big( \boldsymbol{\tau},\boldsymbol{\mu}_1,\boldsymbol{\mu}_2,\Sigma_1,\Sigma_2 \big) $$

a) Given the data, find the parameters $\theta$ using EM algorithm.



In [27]:
# Load the train dataset 
from math import sqrt


#Note: This cell may need multiple tries since singularity of covariance matrix isn't handled

data = np.load('utils/assign_1_data_3.npy')
# The data is a 1000*2 numpy array, where each row is a independent observation, and 
# the columns are measurement in dimension x and y respectively. 
# now write the code to find the parameter theta.
gamma = np.array(np.zeros([1000,2]))
pi = np.random.uniform(0,1,(2,1))
mu = np.random.uniform(1,100,(2,2))
#sigma = np.random.uniform(0,1,(2,2,2))
sigma = np.array([[[1,0],[0,1]],[[10,0],[0,10]]])
#print sigma.shape
step = 0
def multivariateNormal(x_n, mu_k, sigma_k):
	exponent = -0.5*(np.matmul(np.matmul(np.transpose(x_n - mu_k),np.linalg.inv(sigma_k)), (x_n - mu_k)))
	#print exponent
	#print np.linalg.det(sigma_k)
	#print sigma_k
	#print exponent
	#print sqrt((1/(2*3.14*abs(np.linalg.det(sigma_k))))) * exp(exponent)
	return sqrt((1/(2*3.14*abs(np.linalg.det(sigma_k))))) * exp(exponent)
for i in range(100):
	''' The E step '''
	for n in range(1000):
		for k in range(2):
			numerator = pi[k] * multivariateNormal(np.reshape(data[n],(2,1)), np.reshape(mu[k], (2,1)), sigma[k])
			denominator = pi[0] * multivariateNormal(np.reshape(data[n],(2,1)), np.reshape(mu[0], (2,1)), sigma[0]) + pi[1] * multivariateNormal(np.reshape(data[n],(2,1)), np.reshape(mu[1], (2,1)), sigma[1])
			gamma[n,k] = float(numerator)/denominator

	''' The M step '''
	N = np.sum(gamma, axis=0)

	for k in range(2):
		sum_mu = 0
		for n in range(1000):
			sum_mu += gamma[n,k] * data[n]
		mu[k] = sum_mu/N[k]
	
	for k in range(2):
		sum_gamma = np.zeros((2,2))
		for n in range(1000):
			inter = np.reshape(data[n],(2,1)) - np.reshape(mu[k], (2,1))
			sum_gamma += gamma[n,k]*(np.matmul(inter,np.transpose(inter)))
		sigma[k] = (1/N[k])*sum_gamma
	for k in range(2):
		N[k] = N[k]/1000
	step += 1
	print "---------"
	print step
	print "Mu is ", mu, "Sigma is", sigma

---------
1
Mu is  [[ 41.68921421  38.304566  ]
 [ 55.2677562   65.47124439]] Sigma is [[[ 11  -2]
  [ -2   2]]

 [[ 84 -27]
  [-27 174]]]
---------
2
Mu is  [[ 43.9707313   39.8989283 ]
 [ 55.39907389  65.78111617]] Sigma is [[[ 23  -3]
  [ -3   3]]

 [[ 83 -31]
  [-31 168]]]
---------
3
Mu is  [[ 44.92522135  41.68138988]
 [ 55.63276081  66.32553961]] Sigma is [[[ 29  -3]
  [ -3   5]]

 [[ 82 -37]
  [-37 159]]]
---------
4
Mu is  [[ 47.17195369  43.52882184]
 [ 55.81091822  66.97938068]] Sigma is [[[ 29   2]
  [  2   8]]

 [[ 83 -42]
  [-42 151]]]
---------
5
Mu is  [[ 49.67578762  45.70983765]
 [ 55.97150946  68.0404623 ]] Sigma is [[[ 34   7]
  [  7  12]]

 [[ 86 -47]
  [-47 139]]]
---------
6
Mu is  [[ 52.30133366  47.97063516]
 [ 55.8958947   69.40376536]] Sigma is [[[ 44  13]
  [ 13  19]]

 [[ 91 -50]
  [-50 126]]]
---------
7
Mu is  [[ 54.7099968   50.27333818]
 [ 55.41240436  71.05347504]] Sigma is [[[ 57  21]
  [ 21  28]]

 [[ 94 -48]
  [-48 114]]]
---------
8
Mu is  [[ 56.99

 [ 49.77436452  76.36568809]] Sigma is [[[92 48]
  [48 58]]

 [[19  3]
  [ 3 79]]]
---------
63
Mu is  [[ 60.09975253  55.53169498]
 [ 49.77436452  76.36568809]] Sigma is [[[92 48]
  [48 58]]

 [[19  3]
  [ 3 79]]]
---------
64
Mu is  [[ 60.09975253  55.53169498]
 [ 49.77436452  76.36568809]] Sigma is [[[92 48]
  [48 58]]

 [[19  3]
  [ 3 79]]]
---------
65
Mu is  [[ 60.09975253  55.53169498]
 [ 49.77436452  76.36568809]] Sigma is [[[92 48]
  [48 58]]

 [[19  3]
  [ 3 79]]]
---------
66
Mu is  [[ 60.09975253  55.53169498]
 [ 49.77436452  76.36568809]] Sigma is [[[92 48]
  [48 58]]

 [[19  3]
  [ 3 79]]]
---------
67
Mu is  [[ 60.09975253  55.53169498]
 [ 49.77436452  76.36568809]] Sigma is [[[92 48]
  [48 58]]

 [[19  3]
  [ 3 79]]]
---------
68
Mu is  [[ 60.09975253  55.53169498]
 [ 49.77436452  76.36568809]] Sigma is [[[92 48]
  [48 58]]

 [[19  3]
  [ 3 79]]]
---------
69
Mu is  [[ 60.09975253  55.53169498]
 [ 49.77436452  76.36568809]] Sigma is [[[92 48]
  [48 58]]

 [[19  3]
  [ 3

In [28]:
# Parameters are given by:
print "Final mu(s) are ", mu
print "Final sigmas are ", sigma

Final mu(s) are  [[ 60.09975253  55.53169498]
 [ 49.77436452  76.36568809]]
Final sigmas are  [[[92 48]
  [48 58]]

 [[19  3]
  [ 3 79]]]


In [ ]:
# Visualize the entire data by plotting them as points in a 2-D canvas.  
# Show the estimated means and the standard deviations.


# Clustering

For clustering we covered two algorithms

1) K-means : An iterative method to get 'K' clusters, initializing them randomly

2) Hirarchical : An iterative method to get a dendogram of clustering with various numbers of cluster centers.

### K-means Clustering

We initialize $K$ cluster centers $\{ c_1,c_2 ,... c_k\}$for $K$-clusters randomly. All the data points are assigned a cluster index $D_i \in \{ 1,2,...,k\}$, based on the closest cluster center to each point.

Now, for each cluster, the cluster centers are re-evaluated as the mean of all the points in the center.

$$
c_i = mean(\{ X_j | D_j = i \})
$$
This process continues till convergence.


## Question 4

The dataset contains 1000  color images.Convert them to grayscale images. We need to cluster them into various $n$ clusters based on the similarity of their histograms. For each image, find the histogram with bin size 25 (last bin of 30;i.e.225-255;giving you 10 bins). Now treating each of these bins as seperate dimensions, find:

a) Cluster Centers for $n = 5$ clusters, with $L_2$ distance criteria for measuring distance between a pair of images.

b) **Bonus**: Use Earth Movers Distance in the above problem.

In [30]:
# For this problem we will be using the 1000 test images of CIFAR-10 dataset.
## Load the data from the following link
# https://www.cs.toronto.edu/~kriz/cifar.html
import cPickle

def unpickle(filetoUnpickle):
    with open(filetoUnpickle, 'rb') as fo:
        dict = cPickle.load(fo)
    return dict

#Note: I have added the test_batch files to my utils

filetoUnpickle = 'utils/test_batch'
dict = unpickle(filetoUnpickle)
#print dict['data'].shape
data = dict['data'][:1000,:]
#print data.shape
image_bins = np.zeros((1000, 10))
n = 5
centroids = np.random.uniform(0,100,(5,10))


In [34]:
# Convert it to grayscale values
def belongsTo(data, centroids):
	min = distance(data,centroids[0])
	index = 0
	for i in range(1,5):
		if distance(data,centroids[i]) < min:
			index = i
	return index

def distance(a, b):
    return np.linalg.norm(a - b)

def togrey(a):
	return (0.2125 * a[0] + 0.7154 * a[1] + 0.0721 * a[2])

def convertToGreyAndBin(image_bins):
	for i in range(1000):
		a = data[i]
		#print a
		b = a.reshape((3,1024))
		#print b
		c = np.transpose(b)
		#print c
		#d = np.reshape(32,32,3)
		e = np.apply_along_axis(togrey, 1, c)
		#print e.shape	
		#grey[i] = e
		for j in range(1024):
			index = e[j]/25
			if int(index) == 10:
				image_bins[i][9] += 1
			else:
				image_bins[i][int(index)] += 1
		#print image_bins[i]
		#print grey[i]
	return image_bins
image_bins =  convertToGreyAndBin(image_bins)

In [ ]:
# find the histograms and get a 10-dimensional representation of each images.


In [35]:
# Use K-means to find  out the number of cluster centers.
step = 0
for i in range(100):
	step +=1
	c1 = []
	c2 = []
	c3 = []
	c4 = []
	c5 = []
	for j in range(1000):
		index = belongsTo(image_bins[j],centroids)
		if index == 0:
			c1.append(j)
		if index == 1:
			c2.append(j)
		if index == 2:
			c3.append(j)
		if index == 3:
			c4.append(j)
		if index == 4:
			c5.append(j)
	#print c1,c2,c3,c4,c5
	#print len(c1)
	if step > 1:
		prev_centroids = centroids
	if len(c1) > 0:
		centroids[0] = np.mean(np.take(image_bins,c1, axis=0) , axis=0)
	if len(c2) > 0:
		centroids[1] = np.mean(np.take(image_bins,c2, axis=0) , axis=0)
	if len(c3) > 0:
		centroids[2] = np.mean(np.take(image_bins,c3, axis=0) , axis=0)
	if len(c4) > 0:
		centroids[3] = np.mean(np.take(image_bins,c4, axis=0) , axis=0)
	if len(c5) > 0:
		centroids[4] = np.mean(np.take(image_bins,c5, axis=0) , axis=0)

print centroids

[[   15.83333333    14.66666667    39.66666667    79.83333333    86.5
     94.83333333    90.83333333    91.83333333   117.5         1416.5       ]
 [    0.            12.5           42.5           57.5          101.5
   1170.5          507.           122.5           34.             0.        ]
 [   35.33333333   104.           182.           180.66666667
    116.66666667    72.            52.            58.            60.66666667
   1186.66666667]
 [   20.45454545    79.18181818    97.81818182   135.36363636   150.           131.
    128.09090909   125.54545455   253.45454545   927.09090909]
 [   91.94184839   163.25233645   242.03530633   295.65524403
    310.24299065   282.74350987   247.95430945   191.50363448
    131.82554517    90.84527518]]


In [ ]:
# Visualize cluster means to see what they look like.


# References

Useful references will be added shortly.

1) Linear Regression
  * [Wikipedia](https://en.wikipedia.org/wiki/Linear_regression)

2) Logistic Regression
  * [Wikipedia](https://en.wikipedia.org/wiki/Logistic_regression)
  * [Win Vector Blog](http://www.win-vector.com/blog/2011/09/the-simpler-derivation-of-logistic-regression/)
  * [Renselaer Course Slides](http://www.cs.rpi.edu/~magdon/courses/LFD-Slides/SlidesLect09.pdf)
  
3) EM
  * [Cambridge Tutorial](http://www.cs.huji.ac.il/~yweiss/emTutorial.pdf)
  * [Chapter 9 - Pattern Recognition and Machine Learning by Christopher M. Bishop](http://www.rmki.kfki.hu/~banmi/elte/bishop_em.pdf)
  * [Wikipedia](https://en.wikipedia.org/wiki/Expectation%E2%80%93maximization_algorithm)
  
4) K-means
  * [Wikipedia](https://en.wikipedia.org/wiki/K-means_clustering)